services:
  - type: web
    name: be-todo
    env: docker
    plan: free
    dockerfilePath: ./todo-app/backend/Dockerfile
    dockerContext: ./todo-app/backend
    envVars:
      - key: DB_HOST
        value: dpg-d81v770js32c738edj0g-a.oregon-postgres.render.com
      - key: DB_USER
        value: todo_db_q74m_user
      - key: DB_PASSWORD
        value: ggJjiD3Rx2aSjJO1t3uA2GJqr5AJhjS3
      - key: DB_NAME
        value: todo_db_q74m
      - key: DB_PORT
        value: 5432
      - key: PORT
        value: 10000

  - type: web
    name: fe-todo
    env: docker
    plan: free
    dockerfilePath: ./todo-app/frontend/Dockerfile
    dockerContext: ./todo-app/frontend
    envVars:
      - key: REACT_APP_API_URL
        value: https://be-todo-02240365.onrender.com